spring.application.name=Gateway-Ms
server.port=9091

# Quiz Service
spring.cloud.gateway.routes[0].id=Quiz-Service
spring.cloud.gateway.routes[0].uri=http://quiz-service:8081
spring.cloud.gateway.routes[0].predicates=Path=/quiz/**

# Question Service
spring.cloud.gateway.routes[1].id=Question-Service
spring.cloud.gateway.routes[1].uri=http://question-service:8082
spring.cloud.gateway.routes[1].predicates=Path=/question/**

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka