name: Build Project

on:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-latest

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Java 17
    uses: actions/setup-java@v3
    with:
      distribution: temurin
      java-version: 17

  - name: Give permission to mvnw
    run: chmod +x mvnw

  - name: Build Eureka Server
    working-directory: eureka-server
    run: ./mvnw clean install

  - name: Build Gateway Service
    working-directory: gateway-ms
    run: ./mvnw clean install

  - name: Build Question Service
    working-directory: question-ms
    run: ./mvnw clean install

  - name: Build Quiz Service
    working-directory: quiz-ms
    run: ./mvnw clean install
